---
base:
  config:
    db:
      hostname: db.finalbi.com
      port: 3307
      dbname: whale_ums
    nacos:
      hostname: nacos.finalbi.com
      port: 8848

spring:
  profiles: dev
  application:
    name: ums-admin-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.db.hostname}:${base.config.db.port}/${base.config.db.dbname}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  scan:
    base-packages: com.finalbi.whale.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

mybatis:
  type-aliases-package: com.finalbi.whale.provider.domain
  mapper-locations: classpath:mapper/*.xml

---
base:
  config:
    db:
      hostname: 192.168.79.90
      port: 3307
      dbname: whale_ums
    nacos:
      hostname: 192.168.79.90
      port: 8848

spring:
  profiles: localtest
  application:
    name: ums-admin-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.db.hostname}:${base.config.db.port}/${base.config.db.dbname}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  scan:
    base-packages: com.finalbi.whale.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

mybatis:
  type-aliases-package: com.finalbi.whale.provider.domain
  mapper-locations: classpath:mapper/*.xml

---

base:
  config:
    db:
      hostname: 172.26.159.53
      port: 5100
      dbname: whale_ums
    nacos:
      hostname: 172.26.159.53
      port: 9554

spring:
  profiles: test
  application:
    name: ums-admin-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.db.hostname}:${base.config.db.port}/${base.config.db.dbname}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: a[jkhg.1ssk
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  scan:
    base-packages: com.finalbi.whale.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

mybatis:
  type-aliases-package: com.finalbi.whale.provider.domain
  mapper-locations: classpath:mapper/*.xml